# Generated by Django 2.0.3 on 2018-05-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GNSSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=8)),
                ('coordinate', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=15)),
                ('satellitesCount', models.CharField(max_length=2)),
            ],
        ),
    ]
