# Generated by Django 2.0.3 on 2018-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewNV08C', '0002_driverstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnssdata',
            name='dataFlag',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
